faction:
  max-registry-length: 10 # 10 characters
  max-display-length: 10 # 10 characters
  max-tag-length: 3 # 3 characters for any type of character
  active-member-threshold: 60
  default:
    motd: "Newly created faction"
    tag: "IFF"
    open-type: "INVITE_ONLY" # Options: PUBLIC; INVITE_ONLY; CLOSED
    frozen: false
    permanent: false
    start-balance: 0
    start-power: 20
    start-max-power: 20

performance:
  ram:
    claim-garbage-collector: 6000 # default: 6000 ticks (5 minutes). 20 ticks = 1 second. Smaller value will reduce RAM usage, but increases stress on the cpu for cleaning. A too small value will overload your disk, due to everything needing to be loaded and instantly being rejected from ram again

language:
  default-local: "en_us" # Change this to your server main language, as long as a file with this name exists within lang/ folder

zones:
  safezone:
    translation-id: "territory.safezone"
    registry: "__glb:safezone__"
    color: 0x00bfff
    managed: true # Determines if the claim will be handled by improved factions
    protection: true
    pvp: false
  warzone:
    translation-id: "territory.warzone"
    registry: "__glb:warzone__"
    color: 0xb30000
    managed: true # Determines if the claim will be handled by improved factions
    protection: true
    pvp: true
  unclaimable:
    translation-id: "territory.unclaimable"
    registry: "__glb:unclaimable__"
    color: 0xb30000
    managed: false # This will just prevent the chunks from being claimed


world:
  disabled-worlds: # A list of worlds that don't allow improved factions
  #  - "Disabled faction world"
  enabled-worlds: # When having too many worlds and only want a small amount to be faction worlds, use this list. This list will calculate a disabled worlds list
#  - "Enabled faction world"

################# Advanced config options #####################
#
# A database always syncs up ith the server, meaning that you can run this plugin on multiple
# server while still keeping your data synchronized
#
# Useful with Multipaper, Velocity, BungeeCord, etc
#
# This will save RAM on the minecraft server side.
# Only one database should be selected with true
# When no database is selected, it will run locally using the plugin data folder
#
storage:
  use-mysql: false
  mysql: # Only when use-mysql is set to true
    host: "localhost" # Host is the ip address of the mysql server
    port: "3306" # Port is the port the service is listing at
    user: "root" # The user this plugin is allowed to use. Note: Don't use root, create a new user with permissions to just manage improved factions tables
    password: "1234" # The password of the user given above
